apiVersion: v1
kind: Namespace
metadata:
  name: ml-pipeline-staging
  labels:
    env: staging
    app: ml-pipeline
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-pipeline-production
  labels:
    env: production
    app: ml-pipeline
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    app: mlflow
